environments:
 UAT:
    environment_variables:
      nexus_ip: 10.10.10.10
    pipelines:
      - image-creation
pipelines:
  image-creation:
    group: pipeline-as-a-code
    materials:
      packer-aws:  # this is the name of material
        git: https://github.com/RameshBahavathi/gocd-yaml-config-example.git
        branch: master
        destination: packer
      control:  # this is the name of material
        git: https://github.com/RameshBahavathi/gocd-yaml-config-example.git
        branch: master
        destination: control
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: mkdir testdir
